INSERT INTO APP_USER (USER_NAME, FULL_NAME, USER_TYPE)
VALUES ('test', 'Test User', 'STUDENT');

INSERT INTO APP_USER (USER_NAME, FULL_NAME, USER_TYPE)
VALUES ('admin', 'Administrator', 'ADMIN');

INSERT INTO APP_USER (USER_NAME, FULL_NAME, USER_TYPE)
VALUES ('guest', 'Special Guest', 'GUEST');

INSERT INTO APP_USER (USER_NAME, FULL_NAME, USER_TYPE)
VALUES ('acurrass', 'Angel Curras Sanchez', 'STUDENT');

INSERT INTO APP_USER (USER_NAME, FULL_NAME, USER_TYPE)
VALUES ('leonb', 'Leon Beckert', 'STUDENT');

INSERT INTO APP_USER (USER_NAME, FULL_NAME, USER_TYPE)
VALUES ('mathemann', 'Jan Weller', 'STUDENT');


